accelerator: gpu
accumulate_grad_batches: 16
adam_epsilon: 1.0e-08
amp_backend: native
amp_level: null
auto_lr_find: false
auto_scale_batch_size: false
auto_select_gpus: false
benchmark: null
callbacks:
- !!python/object:pytorch_lightning.callbacks.lr_monitor.LearningRateMonitor
  _lr_sch_names: []
  log_momentum: false
  logging_interval: step
  lrs: {}
- !!python/object:pytorch_lightning.callbacks.early_stopping.EarlyStopping
  _check_on_train_epoch_end: null
  best_score: !!python/object/apply:torch._utils._rebuild_tensor_v2
  - !!python/object/apply:torch.storage._load_from_bytes
    - !!binary |
      gAKKCmz8nEb5IGqoUBkugAJN6QMugAJ9cQAoWBAAAABwcm90b2NvbF92ZXJzaW9ucQFN6QNYDQAA
      AGxpdHRsZV9lbmRpYW5xAohYCgAAAHR5cGVfc2l6ZXNxA31xBChYBQAAAHNob3J0cQVLAlgDAAAA
      aW50cQZLBFgEAAAAbG9uZ3EHSwR1dS6AAihYBwAAAHN0b3JhZ2VxAGN0b3JjaApGbG9hdFN0b3Jh
      Z2UKcQFYCQAAADE0Nzg3MTY2NHECWAMAAABjcHVxA0sBTnRxBFEugAJdcQBYCQAAADE0Nzg3MTY2
      NHEBYS4BAAAAAAAAAAAAgP8=
  - 0
  - !!python/tuple []
  - !!python/tuple []
  - false
  - !!python/object/apply:collections.OrderedDict
    - []
  check_finite: true
  divergence_threshold: null
  min_delta: 0.0
  mode: max
  monitor: val_AUROC
  patience: 10
  stopped_epoch: 0
  stopping_threshold: null
  strict: true
  verbose: true
  wait_count: 0
- !!python/object:pytorch_lightning.callbacks.progress.tqdm_progress.TQDMProgressBar
  _current_eval_dataloader_idx: null
  _enabled: true
  _main_progress_bar: null
  _predict_progress_bar: null
  _process_position: 0
  _refresh_rate: 10
  _test_progress_bar: null
  _trainer: null
  _val_progress_bar: null
- !!python/object:pytorch_lightning.callbacks.gradient_accumulation_scheduler.GradientAccumulationScheduler
  epochs:
  - 0
  scheduling:
    0: 16
check_val_every_n_epoch: 1
checkpoint_callback: false
deactivate_earlystopping: false
default_root_dir: null
detect_anomaly: false
deterministic: true
devices: '1'
dropout_prob: 0.5
enable_checkpointing: true
enable_model_summary: true
enable_progress_bar: true
encoder_learning_rate: 5.0e-06
fast_dev_run: false
flush_logs_every_n_steps: null
gpus: null
gradient_checkpointing: true
gradient_clip_algorithm: null
gradient_clip_val: null
hpc_exp_number: null
ipus: null
label_set: 1,0
learning_rate: 3.0e-05
limit_predict_batches: null
limit_test_batches: 1.0
limit_train_batches: 1.0
limit_val_batches: 1.0
loader_workers: 8
local_logger: !!python/object/apply:logging.getLogger
- __main__
log_every_n_steps: 50
log_gpu_memory: null
logger: true
max_epochs: 20
max_length: 1536
max_steps: -1
max_time: null
metric_mode: max
min_epochs: 1
min_steps: null
monitor: val_AUROC
move_metrics_to_cpu: false
multiple_trainloader_mode: max_size_cycle
nb_trials: 24
nr_frozen_epochs: 1
num_nodes: 1
num_processes: null
num_sanity_val_steps: 0
overfit_batches: 0.0
patience: 10
per_device_eval_batch_size: 8
per_device_predict_batch_size: 8
per_device_test_batch_size: 8
per_device_train_batch_size: 8
perform_prediction: false
perform_testing_with_best_checkpoint: false
perform_testing_with_checkpoint: false
plugins: null
precision: 32
predict_csv: /home/arash.mozhdehi/GPU_STEP/STEP-main/data/generated/test_samples_output.csv
prediction_checkpoint: null
prediction_output_file: /home/arash.mozhdehi/GPU_STEP/STEP-main/data/generated/ml/predict.txt
prepare_data_per_node: null
process_position: 0
profiler: null
prog_arg_string:
- src/ppi_finetuning.py
- --accelerator
- gpu
- --devices
- '1'
- --num_sanity_val_steps
- '0'
prog_cwd: /home/arash.mozhdehi/GPU_STEP/STEP-main
prog_hostname: fg3
progress_bar_refresh_rate: 10
reload_dataloaders_every_n_epochs: 0
replace_sampler_ddp: false
resume_from_checkpoint: null
save_own_checkpoint: false
save_top_k: 1
seed: 3
stochastic_weight_avg: false
strategy: dp
sync_batchnorm: false
terminate_on_nan: null
test_csv: /home/arash.mozhdehi/GPU_STEP/STEP-main/data/generated/test_pairs.csv
test_tube_log_path: /home/arash.mozhdehi/GPU_STEP/STEP-main/test_tube/logs
testing_checkpoint: null
tpu_cores: null
track_grad_norm: -1
train_csv: /home/arash.mozhdehi/GPU_STEP/STEP-main/data/generated/train_pairs.csv
val_check_interval: 0.5
valid_csv: /home/arash.mozhdehi/GPU_STEP/STEP-main/data/generated/val_pairs.csv
warmup_steps: 200
weight_decay: 0.01
weights_save_path: null
weights_summary: null
